### ISSUE TITLE
BeanCopy forced flag not working

### ISSUE THREAD

**Issue by mbjelac** [oblac/jodd#209]
affects version: 3.6.5

test

```
import ...

public class JoddHelperTest {

    public static class PropertyBean {
        public int number;
        public PropertyBean child;
    }

    @Test
    public void joddBeanUtilsUpgrade() throws Exception {

        PropertyBean bean = new PropertyBean();

        Properties props = new Properties();

        props.put("number", 42);
        props.put("child.number", 43);
        props.put("nonExistantNumber", 142);
        props.put("nonExistantChild.number", 143);

        BeanCopy.fromMap(props).toBean(bean).forced(true).copy();

        assertThat(bean.number, is(42));
        assertThat(bean.child.number, is(43));
    }
}
```

fails with

```
jodd.bean.BeanException: Map key not found: nonExistantChild. Invalid property: Properties#nonExistantChild.number (Properties#nonExistantChild, forced=false)
	at jodd.bean.BeanUtilBean.getSimpleProperty(BeanUtilBean.java:145)
	at jodd.bean.BeanUtilBean._getIndexProperty(BeanUtilBean.java:259)
	at jodd.bean.BeanUtilBean.getIndexProperty(BeanUtilBean.java:251)
	at jodd.bean.BeanUtilBean.resolveNestedProperties(BeanUtilBean.java:33)
	at jodd.bean.BeanUtilBean.getProperty(BeanUtilBean.java:540)
	at jodd.bean.BeanUtil.getProperty(BeanUtil.java:115)
	at jodd.bean.BeanVisitor.visit(BeanVisitor.java:123)
	at jodd.bean.BeanCopy.copy(BeanCopy.java:182)
	at JoddHelperTest.joddBeanUtilsUpgrade(JoddHelperTest.java:35)
```

note the "forced=false" parameter log...

anyway, this should be expected behaviour and can be avoided using silent=true in other parts of the API. how to specify silent=true in `BeanCopy`?

**Comment by igorspasic** [comment]
Hmm, this is tricky.

This fails because `nonExistantChild.number` is the property name - including the dot. The proper way to read this value using BeanUtil is `BeanUtil.getProperty(props, "[nonExistantChild.number]`").

But even if we have this reading correctly, it will never set the property `child.number` in above example, since the property name _includes_ the dot. At the destination you have `child`.`number` and that are **two** properties. In other words, there is difference between:

+ `child.number` - eg this is `getChild().setNumber()` - i.e. a _nested_ property
+ `[child.number]` - eg this is `get("child.number")`. - ie a _simple_ property

Maybe we can make difference on how properties are set depending on the source. For example, if `child.number` is read from a `Map`, we can think this is a nested property. This can be default behavior of `BeanCopy` that can be changed, if needed. Let me try this...

**Comment by igorspasic** [comment]
Ok, I have a solution :) It works for:
+ map -> bean
+ map -> map
+ bean -> bean

However, the bean -> map is not working. Here is an example:

	@Test
	public void testFromBeanToMap() throws Exception {
		PropertyBean beanSource = new PropertyBean();

		beanSource.number = 42;
		beanSource.child = new PropertyBean();
		beanSource.child.number = 43;

		Properties propsDest = new Properties();

		BeanCopy.fromBean(beanSource).toMap(propsDest).includeFields(true).copy();

		assertThat(propsDest.size(), is(2));
		assertThat((Integer) propsDest.get("number"), is(42));
		assertThat((Integer) propsDest.get("child.number"), is(43));   // NOT WORKING
	}

The problem is that `child.number` does not exist, only the `child' that is `PropertyBean`. To make this work we would need to know that `child` value is actually a java bean that can be copied to a `Map`. But I don't know how to figure out this? In other words, how to know that `child`s value is a bean that can be 'flatten'.

**Comment by igorspasic** [comment]
Do you think that this behavior is ok?

**Comment by igorspasic** [comment]
Also, there is another issue when eg copying to `Properties` is that value is not stored as `String`. But again, imho that is fine, we are blind copying the bean properties.

**Comment by mbjelac** [comment]
sorry for the late reply, i'm swamped these days...
if it works for bean->map, that's fine with me :) - i'm using your lib for loading properties from file to bean, not the other way around
