### ISSUE TITLE
Views from classpath

### ISSUE THREAD

**Issue by Chandu** [oblac/jodd#218]
I have started exploring jodd madvoc and so far looks good/interesting.
I am trying to build a module which can be included as a JAR in a Servlet 3.0 based container and register itself to respond to specific paths.

So far so good, I got it working.
However what I want to do is serve the views (jsp/html) from the files embedded in the jar.
Is there a way to change the view resolver to look for the files in the classpath instead of webapp folder?

**Comment by igorspasic** [comment]
Of course, you can do whatever you want. The key class for resolving the view is `ActionResult` ([source](https://github.com/oblac/jodd/blob/master/jodd-madvoc/src/main/java/jodd/madvoc/result/ActionResult.java)). See some implementations [here](https://github.com/oblac/jodd/tree/master/jodd-madvoc/src/main/java/jodd/madvoc/result).

**Comment by zqq90** [comment]
@Chandu And for other template-engines (`Freemarker`, `Velocity`, etc .. ) are also very easy to DIY,
for example:
https://github.com/zqq90/webit-script/blob/master/webit-script-support/support-jodd3/src/main/java/webit/script/support/jodd3/WebitResult.java

**Comment by Chandu** [comment]
@igorspasic @zqq90 Thank you. I will close this issue shortly.

**Comment by igorspasic** [comment]
Exactly like @zqq90  said :) By default we provide the common JSP dispatcher results, but you can register and use any, like [webit-script](http://zqq90.github.io/webit-script/), `Freemarker`, Soy... etc. Even you can use Jodd to create simple template engine:)

We do not provide any 'official' implementation (maybe soon, in different integration project), since there are several ways how you can deal with the results anyway. Take for example JSON results - it looks simple, yet we find different ways how people want to use them - some want to do automatic serialization etc.

So play with the ActionResults, check documentation... and enjoy :)

**Comment by Chandu** [comment]
I have implemented a quick and dirty ClasspathResult as below and placed my views in the /META-INF/resources and it works!!!

```
public class ClasspathActionResult extends ServletDispatcherResult {
	private static final Logger log = LoggerFactory.getLogger(ClasspathActionResult.class);
	
	@Override
	protected boolean targetExists(ActionRequest actionRequest, String target) {
               //TODO: make it better for final implementation
		return getClass().getResource("/META-INF/resources" + target) != null;
	}
}
```

**Comment by igorspasic** [comment]
Exactly, easy as that :) Feel free to spread the word about the Jodd ;))))
