### ISSUE TITLE
how about add str2map support for special split use cases for stringutil ?

### ISSUE THREAD

**Issue by bwzhang2011** [oblac/jodd#227]
Hi, I encountered some string split use case like key=value pair groups with blank character.e.g
`String str="abc@ccc='123' bb='com.business.process' time='2015-07-10 22:16:32.333'"`. it seems
that such is originated from the `Map<String,String>` and turned it into the string way. but I could not find
some better way to turn the str into map. for I could not directly use split(" ") to do that for the value may have the blank character just like the date pattern(yyyy-MM-dd HH:mm:ss.sss). so any idea for such could turn the` key=value` pair of string into map.

**Comment by igorspasic** [comment]
This is the fastest solution I come with:

	public static void main(String[] args) {
		String str = "abc@ccc='123' bb='com.business.process' time='2015-07-10 22:16:32.333'";

		String[] arr = StringUtil.split(str, "' ");

		for (String line : arr) {
			String[] tuple = StringUtil.splitc(line, "=");

			String key = tuple[0];
			String value = tuple[1];

			if (value.startsWith("'")) {
				value = value.substring(1);
			}
			if (value.endsWith("'")) {
				value = StringUtil.substring(value, 0, -1);
			}
			// add to the map
			System.out.println(key);
			System.out.println(value);

			System.out.println("----------------------------------");
		}
	}

however, it is fragile: The inner value can't have the `'` and there can be only one `=` etc. In other words, you need to do this manually, there is no magic behind this :)

**Comment by bwzhang2011** [comment]
@igorspasic, thanks for feed back. character of '  is just for shown for compiling. the real use case will not include such. but my suggestion that some key value pair split some times is needed and of course like you pointed out. it should be manually done yourself. however, if any idea come up this week I will follow that and check it out for testing.

**Comment by septs** [comment]
syntax similar java.lang.Properties?
```java
String data = "abc@ccc='123' bb='com.business.process' time='2015-07-10 22:16:32.333'";

Props props = new Props();
props.load(data.replace(" ", "\n"));
...
String bb = props.getValue("bb");
```

see http://jodd.org/doc/props.html
see https://github.com/oblac/jodd/blob/master/jodd-props/src/main/java/jodd/props/Props.java#L214

**Comment by bwzhang2011** [comment]
@septs, it's not right to do with jodd props. you could make a test to verify that.

**Comment by igorspasic** [comment]
Yeah, Props looks tempting, but they can't be simple used :)

Anyway, this is looks like specific case to me. It depends on many things, like:
+ value quoting character (`"`,`'`, `[`...),
+ escaping character of a quote for a value,
+ separator character (space, new line, tab...),
+ assign character (`=`, `:`...),
+ escaping character for a key name

Not to mention: what happens when values are collections, arrays etc? Should we convert string to a bean, not only a map? This is very close to deserialization of a bean/map.

On the other hand, writing specific function that solves concrete use case is not too hard; so I believe that such function at the end would be too complex and yet not used much.

Proper (de)serialization can be done with eg JSON; so again, I don't see much value in creating another set of tools that match some proprietary format.

I hope you understand :)

**Comment by igorspasic** [comment]
Yeah, Props looks tempting, but they can't be simple used :)

Anyway, this is looks like specific case to me. It depends on many things, like:
+ value quoting character (`"`,`'`, `[`...),
+ escaping character of a quote for a value,
+ separator character (space, new line, tab...),
+ assign character (`=`, `:`...),
+ escaping character for a key name

Not to mention: what happens when values are collections, arrays etc? Should we convert string to a bean, not only a map? This is very close to deserialization of a bean/map.

On the other hand, writing specific function that solves concrete use case is not too hard; so I believe that such function at the end would be too complex and yet not used much.

Proper (de)serialization can be done with eg JSON; so again, I don't see much value in creating another set of tools that match some proprietary format.

I hope you understand :)

**Comment by bwzhang2011** [comment]
@igorspasic, thanks for  your conclusion and sharing your experience. as your suggestion it could be done with JSON, of course I want to make it like json with key value pair but I don't know how to test wit  h that. no matter what type of it should be with the conversion, it should have some typical convert use cases. would you mind leaving me more about that ? and I think I should close such issue not long.

**Comment by bwzhang2011** [comment]
@igorspasic, any update with such issue ? would you mind leaving us some example to introduce for that ?

**Comment by igorspasic** [comment]
With JSON you can simply serialize your object using the [Json Serializer](http://jodd.org/doc/json/json-serializer.html). It will create JSON string that can be later parsed into a `Map` or back to a bean.

If you don't have access to the creation of the string then you can't use JSON, of course, but go with the code snipped given above. It works for the example, but you might need to make it better :)))

**Comment by bwzhang2011** [comment]
@igorspasic, thanks for feed back. I think it's easy to serialize a map to a json through the Json Serializer but you know they are different format, my format is focused on[key1=value1 key2=value] style. so the better way to handle that is to make the split character to be special way. I agree that there's no common way to do so.
