### ISSUE TITLE
Exclude a property inside a list is not possible in BeanCopy?

### ISSUE THREAD

**Issue by claudineij** [oblac/jodd#232]
I tried exclude a property that is inside a list like this:
<code>BeanCopy.beans(salesOrder, newSalesOrder).exclude("items.id").copy();</code>

But the list "items" was copied with the id in it.
There is some method to do this? This is the expected?

**Comment by igorspasic** [comment]
`BeanCopy` works only shallow. So if you have a list property in source, the reference to the list will be copied to the target bean. In order to more trickery, you are allowed to extend `BeanCopy` and override the method that does the copying.

Soon we will add more java8-friendly interfaces and its going to be easier to do such change without extending.

Hope this helps :) I will close this question, but if you have anything else to say - just let me know!
