### ISSUE TITLE
Can JsonSerializer provide more powerful options?

### ISSUE THREAD

**Issue by liniu** [oblac/jodd#237]
I  use  `JsonSerializer` in many projects, In some cases,we need to exclude `null` value properties ,
and in other cases ,we need options such as :write `null` number as zero, write `null` string as empty, write `null` boolean as `false`.
Is it possible provide more powerful options?

**Comment by liniu** [comment]
Thanks @igorspasic

**Comment by igorspasic** [comment]
Sure, lets go through this :smile_cat: 

We already have option for `excludeNulls` :)

**[1]**

First, the easiest way to deal with the defaults is to have wrapper/adapter for your beans:

    FooJsonWrapper() {
        public String getMe() {
             if (target.me == null) return "";
            return target.me;
        }
        ....
    }

It's like to have a kind of JSON - only model wrapper/adapter on your classes.

**[2]**
You can tweak serialization by using custom `TypeJsonSerializer` implementation. Registration is trivial:

    new JsonSerializer().use(Number.class, new MyNumberSerializer());

And you can see how simple `NumberSerializer` gets:

```
public class NumberJsonSerializer implements TypeJsonSerializer<Number> {
	public void serialize(JsonContext jsonContext, Number value) {
		jsonContext.write(value.toString());
	}
}
```

So with this you can tweak how default implementation works.

Except, in your case, this aint gonna work :)))) Why? Because you want special treatment of `null`. and writing nulls is not in the serializers.

Short story long, I will try to add these options, should be easy. :)))

**Comment by liniu** [comment]
@igorspasic :+1:

**Comment by igorspasic** [comment]
Yap, thats written above, so I am thinking in enabling maybe the null, or adding special Null converter.... working on this, will let you know ;)

**Comment by liniu** [comment]
Thanks @igorspasic ，I am looking forward to the 3.7 version ！
