### ISSUE TITLE
Then the fields of entity less than the columns retruned by sql query, the fields after the missing field all are null.

### ISSUE THREAD

**Issue by account4matt** [oblac/jodd#248]
For example,there is a table:
```
CREATE TABLE subject (
id  bigint NULL AUTO_INCREMENT ,
type  int NULL ,
name  varchar(32) NULL ,
desc  varchar(1024) NULL ,
ctime  bigint NULL ,
PRIMARY KEY (id)
);
```
and some records:

|id|type|name|desc|ctime|
|----|----|----|----|----|
|1|2|name1|desc1|123456789|
|2|1|name2|desc2|123456789|
|3|1|name3|desc3|123456789|
|4|2|name4|desc4|123456789|

and the entity:

```
@DbTable("subject")
public class Subject {

	@DbId("id")
    Long id;

    @DbColumn("type")
    Integer type;
    
    @DbColumn("name")
    String name;

    @DbColumn("ctime")
    Long ctime;

    public Long getId(){
    	return this.id;
    }

    public void getId(Long id){
    	this.id = id;
    }
    
    ...
}

```

The db table contains `desc` column, but the entity dose not.

Execute the following code, the value of `ctime` is null. others are ok.

```
...
Long userId = 1l;
DbOomQuery query = new DbOomQuery(session, "select * from subject where id=:id");
query.setLong("id",userId);
Subject sbj = query.find(Subject.class);
...
```

Execute the following code, this `sbjs` just contains one record , and the value of `ctime` also is null.
```
...
Integer type = 1;
DbOomQuery query = new DbOomQuery(session, "select * from subject where type=:type");
query.setInteger("type",type);
List<Subject> sbjs = query.list(Subject.class);
...
```

Thank you!

**Comment by igorspasic** [comment]
Hi again; lets go with the first issue.

## issue 1

This is expected behavior - let me explain it. You are selecting all columns:

    id, type, name, desc, ctime

and mapping to `Subject`:

    id, type, name, ctime

Default mapper, that matches the result set into the bean goes with following _default_ logic: match as much as possible, and on the first difference, continue with the next bean. That is in the case if table name can not be matched to the result set metadata - and please note that this metadata may return table name in e.g. different letter case.

This means that our matcher on the `desc` field in the result set stops with matching the `Subject` bean and continues with the next bean - which in this case we don't have. So this is the reason why `ctime` is `null`.

### How to fix?

You have few options:

+ Manually select _only_ the columns you map, eg: `select id,type,name,ctime from subject where id=:id` (if you use plain SQL)

+ Use Template-SQL to do the same, automatically: `select $C{subject.*} from $T{Subject subject}...`

+ Use Template-SQL and the magic `DbOomManager.columnAliasType` setting! By default it is not set (i.e. its `null`). It's purpose is to define column aliases in such way that it can provide a table name, so we can match the db bean precisely! The various options in `ColumnAliasType` are just different ways how to set the alias, where `COLUMN_CODE` is the best, as produces the shortest column aliases, but less-readable.

(yeah, we don't have this documented :)

So please, would you be so kind to try first with one above solutions? I guess just using TemplateSQL would solve your issue easily :) Please let me know it goes with you.

**Comment by igorspasic** [comment]
I will explore this issue a bit and try to add some improvements, like:

+ if we match only 1 type, lets match _all_ result set.
+ try your example again

**Comment by account4matt** [comment]
Thank you very much!
We are using the first solution  to avoid bugs come from updating tables's structures. And we would like to try the third solution.
