### ISSUE TITLE
props - read as int, bool

### ISSUE THREAD

**Issue by andrea-bologna** [oblac/jodd#275]
Is there a way to read a prop as int, bool, date?

**Comment by igorspasic** [comment]
Hi!

Not directly - and we did that on purpose :) - since we already have a tool for that, that is quite powerful. It is a class named `Convert`, and the source is [here](https://github.com/oblac/jodd/blob/master/jodd-bean/src/main/java/jodd/typeconverter/Convert.java). So you can write:

    Convert.toIntValue(props.getProperty("foo"))

`Convert` is based on our type converter engine, that can be used for any type conversion, not only for common once. For example, in some projects we often read a `string` property and convert it to a `class`.

So, the `Props` are meant to be slim and string-only, and you have other nice tools to convert that to any type you want; we didn't want to duplicate the code and functionalities.

Does this make sense ?

**Comment by andrea-bologna** [comment]
Well, the philosophy is clear and shareable, but I think that some utility methods for int and bool would be great even in this package, without using another lib and new components (and more verbose code for so simple operations).

**Comment by igorspasic** [comment]
Make sense... One question - for getting the value that does not exist - what would you expect from this API - to return default value (`0`, `false`...) or, to have an optional  default value in the API i.e:

    getPropertyAsInt(name, defaultvalue)

wdyt?

**Comment by andrea-bologna** [comment]
Well, there are different possibilities, I think. One is returning Integer/Boolean with null if prop is not present, another is allowing the default value as you proposed so that we can have int/boolean. For me the only important point is to not have exceptions if the prop is not set.

**Comment by igorspasic** [comment]
Yes, definitely not exceptions! Yap, this variety of options were keeping us away from adding this, but, why not, at least we can add for primitives.

**Comment by andrea-bologna** [comment]
Thank you!

**Comment by igorspasic** [comment]
Added: 

+ `getIntegerValue`
+ `getLongValue`
+ `getBooleanValue`

How this sounds?

**Comment by andrea-bologna** [comment]
Thanks, that's nice, when will it be available?

**Comment by igorspasic** [comment]
It already is :)) Just released new beta on bintray :)
