### ISSUE TITLE
Code copied from other projects should respect the license

### ISSUE THREAD

**Issue by npgall** [oblac/jodd#311]
Hi guys,

You copy/pasted code I own into your project in the following commit, without respecting the Apache 2 license of my code.

https://github.com/oblac/jodd/commit/6aa5f2367e33dc8d57b836b0be5f30f30cf2ba77

You just removed my name as the author, and put your name there instead.

My code is already released with an Apache 2 license, so you are totally free to use it.
But you need to respect the license which means don't plagiarise and please give credit where it is due!

So could you please reinstate my license at the top of those source files? Or alternatively you can add a dependency on my library instead, which contains this code and is in maven central.

You can find maven coordinates here: https://github.com/npgall/concurrent-locks

Thanks!

**Comment by igorspasic** [comment]
Hello @npgall!

This is very embarrassing for us. I am terrible sorry for this and would like to apology. There is a reason why this happened, and involves a third person (and some lack of time), but anyhow - this still does not justify what was done. We had some, well, _strange_ contributions at one point at time.

Again, please forgive me. What I am going to do is to remove all your classes (1f193e5932351761c2a2afe66ea32d3b2614be9b). We are not using it internally and whoever is using it from the outside, we will tell them to use directly your distribution. Also, we will release new version in next 7 days, so even the classes will be removed soon.

Your code is very fine (just looked it). Due to it's size, it is very nice match for Jodd (floppy size!), but I would not just copy/paste it here (we are not using it internally, just moved to java7 :) - unless you want to include it and send a regular pull-request (that we should had insist on in the first place)

Please sorry for this and keep up the good work!

**Comment by igorspasic** [comment]
Because of this issue we added a new label `legal` :)

**Comment by npgall** [comment]
Hi @igorspasic it's no problem at all, and I guessed it was accidental, so thanks for sorting it out! Jodd looks like an interesting project too, I will check it out! Best regards, Niall.

**Comment by igorspasic** [comment]
Thanx for understanding. We really would love to keep the open-source spirit alive!
