### ISSUE TITLE
NullPointerException when use @PetiteInject in application's ready method

### ISSUE THREAD

**Issue by titanseason** [oblac/jodd#336]
How this happened:
1. class _AppWebAplication_ extends PetiteWebApplication
2. Overwrite _ready_() method in _AppWebAplication_
       `@Override
	protected void ready() {
		super.ready();
		IndexGenerator generator = new IndexGenerator();
		generator.generate();
	}`
3. In IndexGenerator:
       `@PetiteInject
	UserDao userDao;	
	public void generate() {
		List<User> list = userDao.listAll(User.class);
	}`

Thus, NullPointerException happens (userDao is null)

**Comment by titanseason** [comment]
I want to do something when the application is started

**Comment by igorspasic** [comment]
Heya @titanseason ! You can't do this:

    IndexGenerator generator = new IndexGenerator();

Because then `Petite` is not in the control of the bean lifecycle. You have created an instance manually, and `Petite` can' inject anything.

So what you can do?

1. You can register `IndexGenerator` as `PetiteBean` and _lookup_ for it (`getBean`), instead of calling `new`.

2. Or you can just _wire_ it: `petiteContainer.wire(generator)`, without adding instance in the container. Of course, you can `addBean` later.

Hope this helps!

**Comment by titanseason** [comment]
Tks, @igorspasic , now my app back to normal nomal !

I overwrite ready() method in AppWebAplication
`	@Override
	protected void ready() {
		super.ready();
		PetiteContainer petite = providePetiteContainer();
		IndexGenerator generator = petite.getBean(IndexGenerator.class);
		generator.generate();
	}
`

**Comment by igorspasic** [comment]
Perfect :)))
