### ISSUE TITLE
DbQuery setbeans() throw a Exception

### ISSUE THREAD

**Issue by zzk0803** [oblac/jodd#365]
My code ：

    DbQuery query = new DbQuery(connection, "SELECT item_id, item_title, item_link,     item_content, item_rsssend FROM tb_rssitem WHERE tb_rssitem.item_id=:rssitem.id");
            query.setDebugMode();
            query.setBean("rssitem", rssItem);

rssitem：
 private long itemId;
    private String itemTitle;
    private String itemLink;
    private String itemContent;
    private long itemRss;

But Run ：
Exception in thread "main" java.lang.NoSuchMethodError: 

```
jodd.bean.BeanUtil.hasDeclaredProperty(Ljava/lang/Object;Ljava/lang/String;)Z
	at jodd.db.DbQuery.setBean(DbQuery.java:824)
	at zzk.play.dbquery.DbQueryPlay.DbQuery_select(DbQueryPlay.java:34)
	at zzk.play.dbquery.DbQueryPlay.main(DbQueryPlay.java:22)
```

Jodd Version:3.8.0
JDK:1.8

**Comment by igorspasic** [comment]
Hey @zzk0803!

Would you be so kind to check if you have the right version of Jodd jars on your classpath/compilepath? Because `jodd.bean.BeanUtil.hasDeclaredProperty(` was removed some time ago and no way it can be used: https://github.com/oblac/jodd/blob/master/jodd-db/src/main/java/jodd/db/DbQuery.java

It looks to me as you have the old version of `jodd-db` and the new version of `jodd-bean`.

**Comment by zzk0803** [comment]
thank you,it's work
i just download in Jodd Official website,not maven...
forgive my pool english...

**Comment by igorspasic** [comment]
No problem!
