### ISSUE TITLE
benchmark for jodd json done by library jsoniter 

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#382]
I have read an article about a new json parser -> http://jsoniter.com/

The interesting part of this new library is the available benchmark - jodd json has been benchmarked by jsoniter.

see https://github.com/json-iterator/java-json-benchmark

maybe this benchmark can be used for optimizing jodd json - if needed and wanted ;-)

issue is only for information :-)

**Comment by igorspasic** [comment]
Nice!!! I already found this one, but kind of forgot it:))
We might check what they did and to see if we can make it even faster!

**Comment by slandelle** [comment]
@igorspasic The first/main difference with those new parsers comes from binding, as they do code generation for the binders, a la protobuf, instead of Java reflection. I'd be curious to see how it compares when binding to a Java AST (non POJOs, but Lists and Maps).

Then, I'd be also curious to see how it fares wrt correctness, see http://seriot.ch/parsing_json.php.
From what I saw with Boon, performance started to deteriorate as the library was fixing more corner cases.

**Comment by igorspasic** [comment]
Yes @slandelle , I had something like code generation in mind for some point: actually it would be JSON structure definition in java, e.g. so we basically skip the parsing as we just consume the json right away. However, not soon :)

You are right about the corner cases, I wonder how many JSON libraries do convert to `BigInteger` or `BigDecimal` when number gets huge ;))

So in short, we will not do anything crazy, but just to check if maybe we can improve something. Plus we gonna ask jsoniter to also make a validator for json parsers, too. Yay!

**Comment by slandelle** [comment]
Looking forward to it :)
