### ISSUE TITLE
Throw Exception java.lang.StringIndexOutOfBoundsException while use http-jodd

### ISSUE THREAD

**Issue by JameLeong** [oblac/jodd#432]
I used jodd-http to request data，the version was 3.9.1,but it  threw exception

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -9
	at java.lang.String.substring(String.java:1967)
	at jodd.http.HttpResponse.readFrom(HttpResponse.java:163)
	at jodd.http.HttpTransport.send(HttpTransport.java:53)
	at jodd.http.HttpRequest.send(HttpRequest.java:451)
```
And I found the code below at the method jodd.http.HttpResponse.readFrom

```
		if (line != null) {

			line = line.trim();

			int ndx = line.indexOf(' ');
			httpResponse.httpVersion(line.substring(0, ndx));

			int ndx2 = line.indexOf(' ', ndx + 1);
			httpResponse.statusCode(Integer.parseInt(line.substring(ndx, ndx2).trim()));

			httpResponse.statusPhrase(line.substring(ndx2).trim());
		}
```

in my situation,the value of the line is 'HTTP/1.1 200',and this method can only process response state with reason-phrase element,like 'HTTP/1.1 200 OK'
[see here](https://github.com/spring-projects/spring-boot/issues/6548)

**Comment by igr** [comment]
Hey @JameLeong!

I believe you are looking at the old code, since this was fixed. See: https://github.com/oblac/jodd/blob/master/jodd-http/src/main/java/jodd/http/HttpResponse.java#L194

Thank you for reporting! Please, check which version you are using, maybe you have some old jars on your classpath, that can happen.
