### ISSUE TITLE
potential licence issue for class jodd/util/BCrypt.java

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#441]
Hi,

Is the licence header for file `jodd/util/BCrypt.java` correct?
It seems that jodd is using this file as copy from http://www.mindrot.org/projects/jBCrypt and therefore the licence header from [here](http://www.mindrot.org/files/jBCrypt/LICENSE) should be used.

Bye,
Sascha

**Comment by igr** [comment]
That is totally true! Btw, am I allowed to use that java code in jodd? I have a need for it for certain user, and since the original one was not published on maven I just copied.

Note to myself: 

+ [ ] check bcrypt
+ [ ] check asm5 code headers as well.
+ [ ] make sure that automatic license updater in IntelliJ does not overwrite these.

**Comment by moh-sushi** [comment]
> Btw, am I allowed to use that java code in jodd?

You can use that code in jodd if the file has its **original** licence header - in my humble opinion.

**Comment by moh-sushi** [comment]
issue seems to be similar to #311.

**Comment by igr** [comment]
Yes will do that. And need to add the acknowledgemnt page.

**Comment by moh-sushi** [comment]
> make sure that automatic license updater in IntelliJ does not overwrite these.

Maybe the gradle plugin [License Gradle Plugin](https://github.com/hierynomus/license-gradle-plugin) can handle this...
