### ISSUE TITLE
usage of the new junit 5 - paradigm ?!

### ISSUE THREAD

**Issue by moh-sushi** [oblac/jodd#453]
Hi,

since [this commit](https://github.com/oblac/jodd/commit/1708de54b9202ae24a6867d856edfe4620bca049) junit 5 will be used overall.

Well, i have few questions using this new major version due to writing jodd tests:
- class / method modifier : package-private can be used now. Is it okay for new tests ? Present tests use public modifier for now. Should present tests be refactored? IMHO : Coding styles should be equals in all places.
- is it okay that tests use experimental features, like `ParameterizedTest` (see http://junit.org/junit5/docs/current/user-guide/#api-evolution-experimental-apis). If tests use one of these features, an upgrade of junit version may broke tests.
- Do any junit 5 - features exist that jodd tests may not use?
- Does the prefix "test" (at test methods) remain? Or is the annotation "Test" sufficient that method is used for tests?

Thanx!

Bye,
Sascha

**Comment by igr** [comment]
Hi, hello!

+ class / method modifier: package-private can be used now. Is it okay for new tests? Present tests use public modifier for now. Should present tests be refactored? IMHO : Coding styles should be equals in all places.

We will use `public` for test methods (like before). I totally agree about the coding style: it has to be unique across the library. Tests probably need more work in this area...

+ is it okay that tests use experimental features, like ParameterizedTest. If tests use one of these features, an upgrade of junit version may broke tests.

I am ok as long as we keep updating and upgrading the code with new versions of junit :)

+ Do any junit 5 - features exist that jodd tests may not use?

No. If we use junit (or any library), we should utilize it to the max. However, please be careful not to use something just because it exists. I had issues with some contribution: they have been using Mockito and instead they could simply avoid it and use tests without it.

+ Does the prefix "test" (at test methods) remain? Or is the annotation "Test" sufficient that method is used for tests?

I would just continue with the same name pattern: `test*` for the methods, and `*Test` for the classes.

**Comment by moh-sushi** [comment]
Which modifier should we use for nested test classes? `public` modifier as well!?
e.g. in PRs #456 and #455 i have used package-private modifier on nested class....

**Comment by igr** [comment]
For nested test classes we didn't have any specification so far... so let's choose, are you ok with the package-private? I am fine.

**Comment by moh-sushi** [comment]
i am ok with `package-private` for nested classes

**Comment by moh-sushi** [comment]
one more question:

Should nestesd class have suffix `*Test` , too?

You have written that you want this suffix on top level test classes. But there is no specification for nestesd classes..

Thx!

**Comment by igr** [comment]
Good question... let's see what JUnit guys says about it...

**Comment by igr** [comment]
Ok. it seems it is not needed. I am ok not to have `*Test` for the nested test classes.

**Comment by moh-sushi** [comment]
idea:

What do you think about (new) help file (markdown) how junit 5 tests should be written.
A kind of collection of the rules which this issue consists of.

**Comment by igr** [comment]
Will do @moh-sushi, good idea!

**Comment by igr** [comment]
https://github.com/oblac/jodd/blob/master/STYLEGUIDE.md
