### ISSUE TITLE
Madvoc 3->4: /list/${id} no longer working, but /list/{id} does

### ISSUE THREAD

**Issue by bentolor** [oblac/jodd#571]
## Current behavior

In Madvoc 3.x I used the following Action method:

```
        @Action(value = "/list/${id}", method = Action.GET)
	public JsonResult getList(@In("id") String id) {
              return GroceryService.get().getGroceryList(id);
	}
```

I converted this for Madvoc 4 into the following code

```
        @Action("/list/${id}") @GET
	public JsonResult getList(@In("id") String id) {
              return GroceryService.get().getGroceryList(id);
	}
```

This does no longer find the Action for URLs like `http://localhost:8080/list/68798a5c-be46-41b8-985a-1b6f32fefd4c`.

Changing to `@Action("/list/{id}")` does work.

## Expected behavior

It's unclear for me when to use the Form `${foo}`  and when `{foo}`. For simplicity I'd like to always use the first form.

## Steps to Reproduce the Problem

The [3.x version can be found here](https://github.com/bentolor/microframeworks-showcase/tree/88e4eda6acacda6d656c343d5bd9ac773d44fa2b/jodd), my [port to 4.x is visible here and will be visible in master,](https://github.com/bentolor/microframeworks-showcase/tree/907d865d340c92dfaafb859095ac5f5a45ecf9fe/jodd) soon.

**Comment by igr** [comment]
Hey @bentolor!

What you experienced is non-backward-compatible change :) There is a way how to setup Jodd to work like before (with `$`), but the new way of using is:

    @Action("/list/{id}")

Why the change? It's simple, the reason is that this format is a standard in e.g. [Swagger](https://swagger.io) and OpenAPI and some other libraries, so the decision was to go with the new format.

That being said, I just noticed that [documentation](https://jodd.org/madvoc/rest.html) is not fully updated :( Will fix that asap.

From now on, just don't use `$` in Madvoc4. Hope this change make sense now...

**Comment by bentolor** [comment]
I saw still remaining usages of `$` – that's what I found confusing. If the change is globally to ommit the `$` and only use `{id}` then I'm really fine with that.. Thanks for your quick response!

**Comment by igr** [comment]
Just to be sure: did you saw that in the documentation? If so, I will fix today :))))

**Comment by bentolor** [comment]
Yes. I re-read the sections about Actions and Injections. That's why I assumed `$` is still up to date.

What I really missed is in the Actions and REST section an example about injecting Paramters as method parameters, which I feel is much more natural than binding to a variable.

**Comment by igr** [comment]
Got it! Will try to fix it all! Thank you for pointing this out, this helps a lot!!!

**Comment by igr** [comment]
@bentolor https://jodd.org/madvoc/rest.html#rest-annotation

At least it is better then before :) THanx again!
