### ISSUE TITLE
Is ValidationContext#addClassChecks thread safe?

### ISSUE THREAD

**Issue by GregoryParks** [oblac/jodd#583]
see: https://github.com/oblac/jodd/blob/v4.1.5/jodd-vtor/src/main/java/jodd/vtor/ValidationContext.java#L98

as we can use Vtor.create().validate(instance), it will call ValidationContext#addClassChecks,
which use HashMap for cache?

**Comment by igr** [comment]
True @GregoryParks, you are right!

But note that this kind of cache is resistant on synchronization issues. In the worst case what could happen is that the input target class gets scanned more than once. And the data would be stored more than once in the cache map, but since the key is the same it would not hurt anything.

Actually, the bigger issue is that this is a `Class` cache, to be honest: we need sort of weak set here that would allow records to disappear once when they become "weak".

I try to be pragmatic here: not to put more code if this does not _hurt_ the functionality.

Nevertheless - I will try to address this, we have `cache` package :)

What do you think?

**Comment by igr** [comment]
From now on you can decide on your own which implementation you would use. Default one is synced but not weak.

**Comment by igr** [comment]
Sorry had to rollback
