### ISSUE TITLE
Send email with one message and one attachment

### ISSUE THREAD

**Issue by jpnffigueiredo** [oblac/jodd#635]
## Current behavior
Send email using only text/html content and one attachment does not add content to body part. Checked using latest version.

## Expected behavior
Is this the expected behavior?

## Steps to Reproduce the Problem

```java
 Email email = Email.create()
    .from("inf0@jodd.org")
    .to("ig0r@gmail.com")
    .subject("test6")
    .textMessage("Hello!")
    .attachment(EmailAttachment.with().content("/b.jpg"));
```

Checking method from SendMailSession message is only added if attachments is empty or totalMessages == 1 or if totalMessages > 1.

```java
jodd.mail.SendMailSession.addBodyData(Email, MimeMessage)
```

**Comment by Kakumle28** [comment]
I ran into the same problem.
By checking the code I came across the following:
class: jodd.mail.SendMailSession
method: private void addBodyData(final Email emailWithData, final MimeMessage msgToSet)

It says there:
if (totalMessages > 1)
Shouldn't that be:
if (totalMessages > 0)

It seems to me that you otherwise miss the case with one message and any attachments.

**Comment by igr** [comment]
Can't believe I missed this!

**Comment by igr** [comment]
Thank you @Kakumle28 and @jpnffigueiredo for this!
