### ISSUE TITLE
ZipUtil Zip slip FLAW

### ISSUE THREAD

**Issue by looly** [oblac/jodd#636]
![image](https://user-images.githubusercontent.com/1432613/45494052-c99e9b80-b7a2-11e8-94e7-92d8901df1df.png)

Like the pic. When `entryName` is `../../../some.sh` can be do any thing.

Please see: [https://snyk.io/research/zip-slip-vulnerability](https://snyk.io/research/zip-slip-vulnerability)

**Comment by neroux** [comment]
I take it you are referring to https://github.com/oblac/jodd/blob/0f989f1e35564d0daaadd61ae3ab5e211085d187/jodd-core/src/main/java/jodd/io/ZipUtil.java#L230

From what I can judge that seems like a valid concern and, using path traversal, one might be able to reach files outside of the given directory

The following code is - as always :D - absolutely untested and I have no clue whether it will work ;) but I guess _something_ of that sort should do the trick

```java
if (file.getCanonicalPath().startsWith((destDir != null ? destDir : new File(".")).getAbsoluteFile()) == false)
{
    // freak out
}
```

There is also a NIO equivalent but I am just way too used to java.io ;D

Being case sensitive, I could imagine issues on Windows if the path does not properly capitalise the names, which could be fixed by lowercasing everything, though that would create issue on *nix. I guess there might be some better way.

@igr

**Comment by igr** [comment]
@neroux Maybe I can simply check if `entryName` starts with `../`?

**Comment by neroux** [comment]
@igr I guess that would still allow for entries such as `./../../../../../../../../../../../../../etc/whatever` or `subdirectory/../../../../../../../../../../../../../etc/whatever`.

One approach could be to generally do a substring search for `..` but I wouldnt be confident enough at this point to guarantee that keeps out all path traversal attempts. The safest way would be probably to normalise the path using `getCanonicalPath` and match that against the destination path (similar to what is mentioned at https://github.com/oblac/jodd/issues/636#issuecomment-422064807).

**Comment by igr** [comment]
@neurox yes yes, i realized that as soon as I hit the bed :)

**Comment by neroux** [comment]
Bedtime is usually the moment when one gets the best ideas :)
