### ISSUE TITLE
@JsonBody type convert failed should be use default value null

### ISSUE THREAD

**Issue by yujinping** [oblac/jodd#677]
When post some request using json,like 
```javascript
{
id:"",
name:"test"
}
```
action like this :
```java
public String test(@JsonBody @In Test test);
```
Test java:
```java
public class Test{
private Long id=null;
private String name=null;
// getter and setter
}
```
## Current behavior

The action throw Number cannot convert for input string ""

## Expected behavior

Convert failed should be null value for default configuration.
include Integer ,Double ,Float ... java bean etc.

If needed ,using some flag to enable exception ,and throw ConvertException or the original.

## Steps to Reproduce the Problem

Json convertor problem.

**Comment by igr** [comment]
The thing here is how the core Jodd converters work. They are strict, in a sense that if you provide an invalid value, it will throw an exception. This was made by design; i.e. it is expected to throw an exception.

This is an easy fix - but need to see how to not change the default behavior, just to add params. For example, I might add a flag for less-strict converters; so you can enable this framework-wide.

**Comment by yujinping** [comment]
yeah , the default mode can be strict ,an optional should be silent(return null and not throw exceptions ).That's a good idea.
