### ISSUE TITLE
HttpRequest.cookies  Only one method is provided, Is so silly

### ISSUE THREAD

**Issue by yesmyyyd** [oblac/jodd#729]
HttpRequest.cookies 
I'm going to assign a random cookie string, but the author only provides one method
Support for arrays and strings is recommended

**Comment by neroux** [comment]
> Maybe it's just lost in translation :)

I am pretty sure it is. Google Translate most likely.

Though, @igr, I am not sure there is any problem with `cookies()` you'd need to fix. It works just beautifully.

**Comment by yesmyyyd** [comment]
The problem has been solved. I used “okhttp”
![image](https://user-images.githubusercontent.com/55237553/65130388-e6158980-da2f-11e9-9ce7-b3b87b16c650.png)

**Comment by yesmyyyd** [comment]
The problem has been solved. I used “okhttp”
![image](https://user-images.githubusercontent.com/55237553/65130471-12c9a100-da30-11e9-8006-359f1d0843cd.png)

**Comment by yesmyyyd** [comment]
@igr   @neroux  
haha,my english is not good.

**Comment by yesmyyyd** [comment]
The problem has been solved satisfactorily at last
 I used “okhttp”
![image](https://user-images.githubusercontent.com/55237553/65130471-12c9a100-da30-11e9-8006-359f1d0843cd.png)

**Comment by neroux** [comment]
Which problem? There was no problem to begin with.

**Comment by igr** [comment]
I don't see a problem, just room for improvement - instead of passing the array of Cookies, we might have `cookies()` that return some sort of collection of cookies and then add/remove using api.

@yesmyyyd 
You can do the same with `header()` in Jodd. Not sure what you mean by that?

**Comment by yesmyyyd** [comment]
@igr 
You can do the same with header() in Jodd.
maybe i didn't find it.

**Comment by igr** [comment]
There are at least 3-4 different header methods in Jodd :))) @yesmyyyd

**Comment by yesmyyyd** [comment]
I see. thank you @igr

**Comment by moh-sushi** [comment]
@yesmyyyd : if there is no problem in Jodd (anymore) - close issue, please.  Thx!

**Comment by neroux** [comment]
> I don't see a problem, just room for improvement - instead of passing the array of Cookies, we might have `cookies()` that return some sort of collection of cookies and then add/remove using api.

There's always room for improvement for just about everything :smiley: Personally I believe the current approach works just fine.

One possibly "improvement" could be to use a `HashSet` instead of an array and extend `Cookie` to hash and equal based on its name, which would allow for easily adding and removing cookies from that hash set with standard calls.

Whether thats necessary is a different subject and IMHO it shouldnt replace the current array approach via `cookies()` as that would break existing code.

But again, this entire discussion started off of a wrong premise :)
