### ISSUE TITLE
Cache module has a bug on version 5.0.13

### ISSUE THREAD

**Issue by pc-fuqq** [oblac/jodd#732]
I found that each time the `AbstractCacheMap.snapshot` method is called, the `lastAccess` property of the` CacheObject` object is reset to the current time, causing the originally expired `CacheObject` object to be revived. In addition, the method `snapshot` should not scan the expired cache, it is better to do a cleanup.

```
 public Map<K, V> snapshot() {
		final long stamp = lock.writeLock();
		try {
			Map<K, V> map = new HashMap<>(cacheMap.size());
			cacheMap.forEach((key, cacheValue) -> map.put(key, cacheValue.getObject()));
			return map;
		}
		finally {
			lock.unlockWrite(stamp);
		}
	}
```

**Comment by neroux** [comment]
I understand you are referring to

https://github.com/oblac/jodd/blob/e4519694f599f2b4fcc0a1838fe83b57652e1d6f/jodd-core/src/main/java/jodd/cache/AbstractCacheMap.java#L314-L324

So you are arguing a call to `snapshot()` should not update `lastAccess` as it is, implicitely, doing right now, because of the call to `getObject`

https://github.com/oblac/jodd/blob/e4519694f599f2b4fcc0a1838fe83b57652e1d6f/jodd-core/src/main/java/jodd/cache/AbstractCacheMap.java#L66-L70

Why would argue so? After all it is accessing the cached object, even if not explicitely, but via the snapshot function.

Just trying to understand the reasoning behind your requests.

**Comment by igr** [comment]
I guess it's because `snapshot()` should not actually get anything, it is more the matter of how to define the contract.

**Comment by neroux** [comment]
Well, `snapshot()` implicitly "gets" the value. But, yes, it is a matter of definition. If `snapshot()` should not update the respective fields, that would be something to be fixed :)

**Comment by igr** [comment]
> "When in doubt, add a flag" - Not Steve Jobs

:)))

**Comment by neroux** [comment]
Nice :+1:
